-- MySQL Script generated by MySQL Workbench
-- Mon Apr 19 04:32:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OnlineShop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OnlineShop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnlineShop` DEFAULT CHARACTER SET utf8 ;
USE `OnlineShop` ;

-- -----------------------------------------------------
-- Table `OnlineShop`.`Languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Languages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `tag` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `tag` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`States`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`States` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Countries_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_States_Contries1_idx` (`Countries_id` ASC) VISIBLE,
  CONSTRAINT `fk_States_Contries1`
    FOREIGN KEY (`Countries_id`)
    REFERENCES `OnlineShop`.`Countries` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `States_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cities_States1_idx` (`States_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cities_States1`
    FOREIGN KEY (`States_id`)
    REFERENCES `OnlineShop`.`States` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `birth_date` DATE NULL,
  `adress` VARCHAR(45) NULL,
  `adress_num` INT NULL,
  `Languages_id` INT NOT NULL,
  `Cities_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_Languages1_idx` (`Languages_id` ASC) VISIBLE,
  INDEX `fk_Users_Cities1_idx` (`Cities_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Languages`
    FOREIGN KEY (`Languages_id`)
    REFERENCES `OnlineShop`.`Languages` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Users_Cities`
    FOREIGN KEY (`Cities_id`)
    REFERENCES `OnlineShop`.`Cities` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Carts_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Carts_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `OnlineShop`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NULL,
  `adress_num` INT NULL,
  `Cities_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Suppliers_Cities1_idx` (`Cities_id` ASC) VISIBLE,
  CONSTRAINT `fk_Suppliers_Cities1`
    FOREIGN KEY (`Cities_id`)
    REFERENCES `OnlineShop`.`Cities` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Currencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Currencies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `tag` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Statuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`UsersStatuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`UsersStatuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Statuses_id` INT NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_UserStates_States_idx` (`Statuses_id` ASC) VISIBLE,
  INDEX `fk_UserStates_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_UserStates_States`
    FOREIGN KEY (`Statuses_id`)
    REFERENCES `OnlineShop`.`Statuses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UserStates_Users`
    FOREIGN KEY (`Users_id`)
    REFERENCES `OnlineShop`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  `description` LONGTEXT NULL,
  `Categories_id` INT NULL,
  `Currencies_id` INT NOT NULL,
  `Suppliers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Products_Categories1_idx` (`Categories_id` ASC) VISIBLE,
  INDEX `fk_Products_Currencies1_idx` (`Currencies_id` ASC) VISIBLE,
  INDEX `fk_Products_Suppliers1_idx` (`Suppliers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Categories1`
    FOREIGN KEY (`Categories_id`)
    REFERENCES `OnlineShop`.`Categories` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_Products_Currencies1`
    FOREIGN KEY (`Currencies_id`)
    REFERENCES `OnlineShop`.`Currencies` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Products_Suppliers1`
    FOREIGN KEY (`Suppliers_id`)
    REFERENCES `OnlineShop`.`Suppliers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`ProductCarts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`ProductCarts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `Carts_id` INT NOT NULL,
  `Products_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ProductCarts_Carts1_idx` (`Carts_id` ASC) VISIBLE,
  INDEX `fk_ProductCarts_Products1_idx` (`Products_id` ASC) VISIBLE,
  CONSTRAINT `fk_ProductCarts_Carts1`
    FOREIGN KEY (`Carts_id`)
    REFERENCES `OnlineShop`.`Carts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ProductCarts_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `OnlineShop`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `OnlineShop`;

DELIMITER $$
USE `OnlineShop`$$
CREATE DEFINER = CURRENT_USER TRIGGER `OnlineShop`.`Users_AFTER_INSERT` AFTER INSERT ON `Users` FOR EACH ROW
BEGIN
	insert into carts (users_id) values (NEW.id);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
