-- MySQL Script generated by MySQL Workbench
-- Wed Apr 21 16:29:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OnlineShop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OnlineShop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnlineShop` DEFAULT CHARACTER SET utf8 ;
USE `OnlineShop` ;

-- -----------------------------------------------------
-- Table `OnlineShop`.`Languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Languages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `tag` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Individuals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Individuals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `birth_date` DATE NULL,
  `Languages_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Individuals_Languages1_idx` (`Languages_id` ASC) VISIBLE,
  CONSTRAINT `fk_Individuals_Languages1`
    FOREIGN KEY (`Languages_id`)
    REFERENCES `OnlineShop`.`Languages` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`IndividualStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`IndividualStatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `IsAdmin` TINYINT(1) NOT NULL,
  `IsNew` TINYINT(1) NOT NULL,
  `IsBanned` TINYINT(1) NOT NULL,
  `Individuals_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_IndividualStatus_Individuals1_idx` (`Individuals_id` ASC) VISIBLE,
  CONSTRAINT `fk_IndividualStatus_Individuals1`
    FOREIGN KEY (`Individuals_id`)
    REFERENCES `OnlineShop`.`Individuals` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `tag` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`States`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`States` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Countries_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_States_Countries1_idx` (`Countries_id` ASC) VISIBLE,
  CONSTRAINT `fk_States_Countries1`
    FOREIGN KEY (`Countries_id`)
    REFERENCES `OnlineShop`.`Countries` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `States_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cities_States1_idx` (`States_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cities_States1`
    FOREIGN KEY (`States_id`)
    REFERENCES `OnlineShop`.`States` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Adresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Adresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Cities_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Adresses_Cities1_idx` (`Cities_id` ASC) VISIBLE,
  CONSTRAINT `fk_Adresses_Cities1`
    FOREIGN KEY (`Cities_id`)
    REFERENCES `OnlineShop`.`Cities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`IndividualAdresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`IndividualAdresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `Adresses_id` INT NOT NULL,
  `Individuals_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_IndividualAdresses_Adresses1_idx` (`Adresses_id` ASC) VISIBLE,
  INDEX `fk_IndividualAdresses_Individuals1_idx` (`Individuals_id` ASC) VISIBLE,
  CONSTRAINT `fk_IndividualAdresses_Adresses1`
    FOREIGN KEY (`Adresses_id`)
    REFERENCES `OnlineShop`.`Adresses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_IndividualAdresses_Individuals1`
    FOREIGN KEY (`Individuals_id`)
    REFERENCES `OnlineShop`.`Individuals` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`PhoneNumbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`PhoneNumbers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `Individuals_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PhoneNumbers_Individuals1_idx` (`Individuals_id` ASC) VISIBLE,
  CONSTRAINT `fk_PhoneNumbers_Individuals1`
    FOREIGN KEY (`Individuals_id`)
    REFERENCES `OnlineShop`.`Individuals` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Individuals_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Carts_Individuals1_idx` (`Individuals_id` ASC) VISIBLE,
  CONSTRAINT `fk_Carts_Individuals1`
    FOREIGN KEY (`Individuals_id`)
    REFERENCES `OnlineShop`.`Individuals` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Individuals_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Suppliers_Individuals2_idx` (`Individuals_id` ASC) VISIBLE,
  CONSTRAINT `fk_Suppliers_Individuals2`
    FOREIGN KEY (`Individuals_id`)
    REFERENCES `OnlineShop`.`Individuals` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Currencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Currencies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `tag` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Products` (
  `idProducts` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  `description` LONGTEXT NULL,
  `Suppliers_id` INT NOT NULL,
  `Currencies_id` INT NOT NULL,
  `Categories_id` INT NULL,
  PRIMARY KEY (`idProducts`),
  INDEX `fk_Products_Suppliers2_idx` (`Suppliers_id` ASC) VISIBLE,
  INDEX `fk_Products_Currencies2_idx` (`Currencies_id` ASC) VISIBLE,
  INDEX `fk_Products_Categories2_idx` (`Categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Suppliers2`
    FOREIGN KEY (`Suppliers_id`)
    REFERENCES `OnlineShop`.`Suppliers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Products_Currencies2`
    FOREIGN KEY (`Currencies_id`)
    REFERENCES `OnlineShop`.`Currencies` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Products_Categories2`
    FOREIGN KEY (`Categories_id`)
    REFERENCES `OnlineShop`.`Categories` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Carts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Orders_Carts2_idx` (`Carts_id` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Carts2`
    FOREIGN KEY (`Carts_id`)
    REFERENCES `OnlineShop`.`Carts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`ProductsCarts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`ProductsCarts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `Carts_id` INT NOT NULL,
  `Products_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ProductsCarts_Carts1_idx` (`Carts_id` ASC) VISIBLE,
  INDEX `fk_ProductsCarts_Products1_idx` (`Products_id` ASC) VISIBLE,
  CONSTRAINT `fk_ProductsCarts_Carts1`
    FOREIGN KEY (`Carts_id`)
    REFERENCES `OnlineShop`.`Carts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ProductsCarts_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `OnlineShop`.`Products` (`idProducts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`ProductOrders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`ProductOrders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Orders_id` INT NOT NULL,
  `Products_idProducts` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ProductOrders_Orders1_idx` (`Orders_id` ASC) VISIBLE,
  INDEX `fk_ProductOrders_Products1_idx` (`Products_idProducts` ASC) VISIBLE,
  CONSTRAINT `fk_ProductOrders_Orders1`
    FOREIGN KEY (`Orders_id`)
    REFERENCES `OnlineShop`.`Orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ProductOrders_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `OnlineShop`.`Products` (`idProducts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `OnlineShop`;

DELIMITER $$
USE `OnlineShop`$$
CREATE DEFINER = CURRENT_USER TRIGGER `OnlineShop`.`Individuals_AFTER_INSERT` AFTER INSERT ON `Individuals` FOR EACH ROW
BEGIN
	insert into carts (Individuals_id) values (NEW.id);
END$$

USE `OnlineShop`$$
CREATE DEFINER = CURRENT_USER TRIGGER `OnlineShop`.`Individuals_AFTER_INSERT_1` AFTER INSERT ON `Individuals` FOR EACH ROW
BEGIN
	insert into IndividualStatus (IsAdmin, IsNew, IsBanned, Individuals_id) values (0, 1, 0, NEW.id);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
